<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \App\Entity\Question implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'correctOption' => [parent::class, 'correctOption', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'options' => [parent::class, 'options', null],
        "\0".parent::class."\0".'orderNumber' => [parent::class, 'orderNumber', null],
        "\0".parent::class."\0".'questionText' => [parent::class, 'questionText', null],
        "\0".parent::class."\0".'quiz' => [parent::class, 'quiz', null],
        'correctOption' => [parent::class, 'correctOption', null],
        'id' => [parent::class, 'id', null],
        'options' => [parent::class, 'options', null],
        'orderNumber' => [parent::class, 'orderNumber', null],
        'questionText' => [parent::class, 'questionText', null],
        'quiz' => [parent::class, 'quiz', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
