<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImageProcess extends \App\Entity\ImageProcess implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null],
        "\0".parent::class."\0".'imageName' => [parent::class, 'imageName', null],
        "\0".parent::class."\0".'processType' => [parent::class, 'processType', null],
        "\0".parent::class."\0".'resultImageFile' => [parent::class, 'resultImageFile', null],
        "\0".parent::class."\0".'resultImageName' => [parent::class, 'resultImageName', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'expiresAt' => [parent::class, 'expiresAt', null],
        'id' => [parent::class, 'id', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'imageName' => [parent::class, 'imageName', null],
        'processType' => [parent::class, 'processType', null],
        'resultImageFile' => [parent::class, 'resultImageFile', null],
        'resultImageName' => [parent::class, 'resultImageName', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
