services:
  - type: web
    name: habesha-tools
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: DATABASE_URL
        fromDatabase:
          name: habesha_db
          property: connectionString
      - key: REMBG_API_KEY
        sync: false
      - key: APP_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 10

databases:
  - name: habesha_db
    databaseName: habesha_tools
    user: habesha_user 