<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSS4TE7B\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSS4TE7B/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSS4TE7B.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSS4TE7B\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSS4TE7B\App_KernelProdContainer([
    'container.build_hash' => 'SS4TE7B',
    'container.build_id' => '707c1234',
    'container.build_time' => 1743375979,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSS4TE7B');
