<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLeSrxS\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLeSrxS/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXLeSrxS.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXLeSrxS\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXLeSrxS\App_KernelProdContainer([
    'container.build_hash' => 'XLeSrxS',
    'container.build_id' => 'ebaf90d9',
    'container.build_time' => 1743376465,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLeSrxS');
