<?php

namespace ContainerQZGZx3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackgroundRemoverTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\BackgroundRemoverType' shared autowired service.
     *
     * @return \App\Form\BackgroundRemoverType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\BackgroundRemoverType'] = new \App\Form\BackgroundRemoverType();
    }
}
