<?php

namespace ContainerQZGZx3P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsageLimitServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\UsageLimitService' shared autowired service.
     *
     * @return \App\Service\UsageLimitService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\UsageLimitService'] = new \App\Service\UsageLimitService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
