<?php

namespace ContainerSS4TE7B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BackgroundRemoverController::success' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\BackgroundRemoverController::process' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController::index' => ['privates', '.service_locator.1.tv8cW', 'get_ServiceLocator_1_Tv8cWService', true],
            'App\\Controller\\LogoRemoverController::edit' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController::process' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController::success' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BackgroundRemoverController:success' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\BackgroundRemoverController:process' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController:index' => ['privates', '.service_locator.1.tv8cW', 'get_ServiceLocator_1_Tv8cWService', true],
            'App\\Controller\\LogoRemoverController:edit' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController:process' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\LogoRemoverController:success' => ['privates', '.service_locator.OGS03.k', 'get_ServiceLocator_OGS03_KService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BackgroundRemoverController::success' => '?',
            'App\\Controller\\BackgroundRemoverController::process' => '?',
            'App\\Controller\\LogoRemoverController::index' => '?',
            'App\\Controller\\LogoRemoverController::edit' => '?',
            'App\\Controller\\LogoRemoverController::process' => '?',
            'App\\Controller\\LogoRemoverController::success' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BackgroundRemoverController:success' => '?',
            'App\\Controller\\BackgroundRemoverController:process' => '?',
            'App\\Controller\\LogoRemoverController:index' => '?',
            'App\\Controller\\LogoRemoverController:edit' => '?',
            'App\\Controller\\LogoRemoverController:process' => '?',
            'App\\Controller\\LogoRemoverController:success' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
        ]));
    }
}
