<?php

namespace ContainerSS4TE7B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoRemoverTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LogoRemoverType' shared autowired service.
     *
     * @return \App\Form\LogoRemoverType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LogoRemoverType'] = new \App\Form\LogoRemoverType();
    }
}
