monolog:
    channels:
        - deprecation
        - security
        - background_remover
        - logo_remover

    handlers:
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: debug
            channels: ["security"]

        background_remover:
            type: stream
            path: "%kernel.logs_dir%/background_remover.log"
            level: debug
            channels: ["background_remover"]

        logo_remover:
            type: stream
            path: "%kernel.logs_dir%/logo_remover.log"
            level: debug
            channels: ["logo_remover"]

        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log" 