framework:
    rate_limiter:
        background_remover:
            policy: 'sliding_window'
            limit: 60
            interval: '60 minutes'
        logo_remover:
            policy: 'sliding_window'
            limit: 60
            interval: '60 minutes' 