<?php

namespace ContainerXLeSrxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OGS03_KService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.OGS03.k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OGS03.k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'imageProcess' => ['privates', '.errored..service_locator.OGS03.k.App\\Entity\\ImageProcess', NULL, 'Cannot autowire service ".service_locator.OGS03.k": it needs an instance of "App\\Entity\\ImageProcess" but this type has been excluded in "config/services.yaml".'],
        ], [
            'imageProcess' => 'App\\Entity\\ImageProcess',
        ]);
    }
}
