<?php

namespace ContainerXLeSrxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageProcessRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ImageProcessRepository' shared autowired service.
     *
     * @return \App\Repository\ImageProcessRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ImageProcessRepository'] = new \App\Repository\ImageProcessRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
