<?php

namespace ContainerXLeSrxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageProcessService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.OGS03.k.App\Entity\ImageProcess' shared service.
     *
     * @return \App\Entity\ImageProcess
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OGS03.k": it needs an instance of "App\\Entity\\ImageProcess" but this type has been excluded in "config/services.yaml".');
    }
}
